### ISSUE TITLE
Upgrade to Puppet 4.x

### ISSUE THREAD

**Issue by imesh** [wso2/puppet-base#13]
Currently WSO2 Puppet Modules use Puppet 3.x. We need to upgrade this to Puppet 4.x:
https://docs.puppet.com/release_notes/

**Comment by DilanUA** [comment]
Closing this issue since we are already working on moving our modules to Puppet 5.x [1][2].
[1] https://github.com/wso2/puppet-base/issues/45
[2] https://github.com/wso2/puppet-base/issues/46
