### ISSUE TITLE
Remove hardcoded server startup scripts

### ISSUE THREAD

**Issue by vinok88** [wso2/puppet-base#14]
Currently, the server startup scripts (wso2server.sh) has been hard-coded. Please parameterise this since WSO2 EI has a different startup script (integrator.sh). Better to have this controllable by the products.

**Comment by chamilad** [comment]
I believe @Vishanth  is working on something similar.

**Comment by DilanUA** [comment]
Closing since this was already addressed by https://github.com/wso2/puppet-base/pull/31
