### ISSUE TITLE
service_name / hostaname: declared more than once in wso2am_runtime/manifests/init.pp

### ISSUE THREAD

**Issue by mkelderm** [wso2/puppet-base#40]
Running puppet on in my client fails; on the puppet server log I see:

2017-09-05 21:25:06,289 ERROR [qtp378607112-60] [puppetserver] Puppet The parameter 'hostname' is declared more than once in the parameter list at /etc/puppetlabs/code/environments/mk01232/modules/wso2am_runtime/manifests/init.pp:87:3

Is this a bug?

**Comment by DilanUA** [comment]
Hi @mkelderm 

Yes, you can consider this as a bug which needs to be fixed. These variables are been initialized twice in the manifest which pops up as an error with the new parser.

We need to remove the additional declarations from the init.pp file.

This will be fixed ASAP in the new release.

**Comment by DilanUA** [comment]
Closing since this will of-course be addressed in wso2am_runtime puppet module with the next major release.
